package template

const defaultTypescriptTemplate = `/* Generated by protoc-gen-tpl. Do not edit! */
{{- range $message := .Messages }}

export interface {{ $message.Name }} {
{{- range $field := $message.Fields }}
  {{- /* Field name */}}
  {{ $field.TypescriptName }}: {{/**/}}
  {{- /* Field type */}}
  {{- $field.TypescriptType }}
  {{- if $field.TypescriptIsArray }}[]{{ end }}
{{- end }}
}
{{- end }}
`
